id: I999E1216
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-28T12:06:27+00:00'
last_modified: '2022-06-09T05:03:25.985813+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W2DB4597
  title: རྟ་ནག་རྣམ་འགྲེལ
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    A6A2:
      image_group_id: I1PD28112
      title: ''
      total_pages: 580
      order: 1
      base_file: A6A2.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
