id: P008180
initial_creation_type: ocr
created_at: 28/03/2020
last_modified_at: 2021-12-17 13:06:24.840022
source_metadata:
  id: bdr:W2DB4597
  title: རྟ་ནག་རྣམ་འགྲེལ
  author: ''
  volumes:
    85feaddfe6d341ec877774b3576f903f:
      image_group_id: I1PD28112
      title: ''
      volume_number: 1
      total_pages: 580
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
